# Generated by Django 4.2.7 on 2023-11-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_count', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('top_description_text', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_description_text', models.CharField(blank=True, max_length=255, null=True)),
                ('bottom_description_text', models.CharField(blank=True, max_length=255, null=True)),
                ('red_text', models.CharField(blank=True, max_length=255, null=True)),
                ('checkable', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_color', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_label_color', models.CharField(blank=True, max_length=255, null=True)),
                ('is_checked', models.CharField(blank=True, max_length=255, null=True)),
                ('has_divider', models.CharField(blank=True, max_length=255, null=True)),
                ('padded', models.CharField(blank=True, max_length=255, null=True)),
                ('has_chat', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district_persian', models.CharField(blank=True, max_length=255, null=True)),
                ('city_persian', models.CharField(blank=True, max_length=255, null=True)),
                ('category_slug_persian', models.CharField(blank=True, max_length=255, null=True)),
                ('last_post_date', models.BigIntegerField(blank=True, null=True)),
                ('first_post_date', models.BigIntegerField(blank=True, null=True)),
                ('brand_model', models.CharField(blank=True, max_length=255, null=True)),
                ('business_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_1', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_2', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_3', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('originality', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('rent', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('unavailable_after', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_enabled', models.CharField(blank=True, max_length=255, null=True)),
                ('suggestion_tokens', models.JSONField(blank=True, null=True)),
                ('elevator', models.CharField(blank=True, max_length=255, null=True)),
                ('parking', models.CharField(blank=True, max_length=255, null=True)),
                ('depot', models.CharField(blank=True, max_length=255, null=True)),
                ('map_type', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, max_length=255, null=True)),
                ('map_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('balcony', models.CharField(blank=True, max_length=255, null=True)),
                ('city_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.city')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawler.posttoken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
