# Generated by Django 4.2.7 on 2023-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='not_elevator',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='elevator',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
