# Generated by Django 4.2.7 on 2023-11-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='house_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
