# Generated by Django 4.2.7 on 2023-11-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_post_not_elevator_alter_post_elevator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='not_depot',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='not_parking',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='depot',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='parking',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
