# Generated by Django 4.2.7 on 2023-11-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_post_house_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
