# Generated by Django 4.2.7 on 2023-11-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_post_not_depot_post_not_parking_alter_post_depot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='has_divider',
        ),
        migrations.RemoveField(
            model_name='post',
            name='note',
        ),
        migrations.RemoveField(
            model_name='post',
            name='padded',
        ),
        migrations.RemoveField(
            model_name='post',
            name='standard_label_color',
        ),
    ]
