# Generated by Django 4.2.7 on 2023-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_remove_post_has_divider_remove_post_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check_cost_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pricing_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
