# Generated by Django 4.2.7 on 2023-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_post_check_cost_limit_post_pricing_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='not_balcony',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
