# Generated by Django 4.2.7 on 2023-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_post_not_balcony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
